# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://github.com/marketplace/actions/action-for-semantic-release

name: Release

on:
  push:
    branches:
      - main

jobs:
  test-workflow:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test-workflow
    runs-on: ubuntu-latest

    permissions:
      contents: write       # to be able to publish a GitHub release
      issues: write         # to be able to comment on released issues
      pull-requests: write  # to be able to comment on released pull requests
      # id-token: write     # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "lts/*"

      # - name: Install dependencies
      #   run: npm clean-install

      # - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      #   run: npm audit signatures

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        # run: npx semantic-release

      - name: Published Release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
