# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://github.com/marketplace/actions/action-for-semantic-release

name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    # name: Test
    uses: ./.github/workflows/job-test.yml

  release:
    # name: Release
    needs: test

    permissions:
      contents: write       # to be able to publish a GitHub release
      issues: write         # to be able to comment on released issues
      pull-requests: write  # to be able to comment on released pull requests
      # id-token: write     # to enable use of OIDC for npm provenance

    uses: ./.github/workflows/job-release.yml
